Feature -  Semaphore CI
Semaphoreapp does not support pip, only setuptools i.e.

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools